version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    commit-message:
      prefix: chore
      include: scope
    groups:
      codeql:
        patterns:
          - "github/codeql-action/*"
      artifact:
        patterns:
          - "actions/*-artifact"

